runtime: nodejs22
entrypoint: npm start 

env_variables:
  PORT: 4000

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
